# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function to run VBJM
#'
#' @param datalist a list object with all data
#' @param paralist a list object with all initial parameters
#' @param eps stopping criteria
#' @param maxiter the maximum number of iterations
#' @return a list
VBJM <- function(datalist, paralist, maxiter = 100L, eps = 1e-4) {
    .Call('_VBJM_VBJM', PACKAGE = 'VBJM', datalist, paralist, maxiter, eps)
}

