// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// VBJM
List VBJM(const List& datalist, const List& paralist, int maxiter, double eps);
RcppExport SEXP _VBJM_VBJM(SEXP datalistSEXP, SEXP paralistSEXP, SEXP maxiterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const List& >::type paralist(paralistSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(VBJM(datalist, paralist, maxiter, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VBJM_VBJM", (DL_FUNC) &_VBJM_VBJM, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_VBJM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
